myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'courses/', views.courses, name='courses'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'order_response/', views.place_order, name='order_response'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'courses/<cour_id>/', views.course_detail, name='course_detail'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myaccount/', views.myaccount, name='my_account'),
    path(r'test_cookie/', views.test_cookie, name='test_cookie'),
    path(r'reset_pwd/', views.reset_pwd, name='reset_pwd'),
]

mysite20/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import home, user_login

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path(r'accounts/login/', user_login, name='user_login'),
]

myapp/models.py
from django.db import models

# Create your models here.
# useful packages
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


class Topic(models.Model):
    """ model for Topic """
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, default='')

    def __str__(self):
        """ overload str function """
        return "Name: {}, Category: {}".format(self.name, self.category)


class Course(models.Model):
    """ model for Course """
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    hours = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    # new fields in Lab7
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return "Topic: {}, Name: {}, Price: {}, For_everyone: {}, Description: {}".format(
            self.topic, self.name, self.price, self.for_everyone, self.description
        )

    def discount(self):
        """ return the discount amount of the price"""
        return float(self.price) * 0.1


class Student(User):
    """ model for Student """
    CITY_CHOICES = [
        ('WS', 'Windsor'),
        ('CG', 'Calgery'),
        ('MR', 'Montreal'),
        ('VC', 'Vancouver')
    ]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='Windsor')
    interested_in = models.ManyToManyField(Topic)
    address = models.CharField(max_length=128, default='')

    def __str__(self):
        return "Username: {}, City:{}, Address: {}".format(self.username, self.city, self.address)


class Order(models.Model):
    ORDER_STATUS = [
        (0, 'Cancelled'),
        (1, 'Order Confirmed'),
    ]
    course = models.ForeignKey(Course, related_name='courses', on_delete=models.CASCADE)
    student = models.ForeignKey(Student, related_name='students', on_delete=models.CASCADE)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=ORDER_STATUS)
    order_date = models.DateField(default=timezone.now)

    def __str__(self):
        return "Course: {}, Student: {}, Levels: {}, Order_status: {}, Order_date: {}".format(
            self.course, self.student, self.levels, self.order_status, self.order_date
        )

myapp/forms.py
from django import forms
from myapp.models import Order


class OrderForm(forms.ModelForm):
    """ based on the Order model to create the form """
    class Meta:
        model = Order
        fields = ('student', 'course', 'levels', 'order_date')
        widgets = {
            'student': forms.RadioSelect(attrs={'class': 'radio'}),
            'order_date': forms.SelectDateWidget(attrs={'class': 'years=date.today()'}),
        }
        Labels = {
            'student': 'Student Name',
            'order_date': 'Order Date',
        }


class InterestForm(forms.Form):
    CHOICES = (
        ('1', 'Yes'),
        ('0', 'No'),
    )

    interested = forms.CharField(widget=forms.RadioSelect(choices=CHOICES))
    levels = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea(), required=False, label="Additional Comments")

myapp/views.py
import smtplib
import string
import random

from django.shortcuts import render, redirect
# Create your views here.

# Import necessary classes
from django.http import HttpResponse, HttpResponseRedirect
# from pandas.tests.extension import decimal
from django.urls import reverse
import datetime
from .forms import *
from .models import Topic, Course, Student, Order
from .admin import CourseAdmin
# from .models import Topic, Course, Student, Order
from .models import *

# lab 8
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# send email
from django.core.mail import send_mail


def home(request):
    """
    default homepage for 127.0.0.1:8000, users can select the landing web-page
    """
    content = "<h1> Welcome! </h1> " \
              "<p> Please select the pages: </p> " \
              "<ul> " \
              "<li> <a href={}> Courses </a></li> " \
              "<li> <a href={}> About </a></li> " \
              "</ul>".format('myapp/', 'myapp/about/')
    return HttpResponse(content)


# Create your views here.
def index0(request):
    """
    the index page of myapp
    """
    # for displaying topics
    top_list = Topic.objects.all().order_by('id')[:10]
    data = {
        'top_list': top_list,
    }
    return render(request, 'myapp/index0.html', data)


# about page
def about(request):
    """
    the about page of myapp
    """
    cookie_val = request.COOKIES.get('about_visits', None)
    if cookie_val is None:  # no cookies
        print('first time!')
        cookie_val = 0

    cookie_val = int(cookie_val) + 1
    text = 'This is an E-learning Website! Search our Topics to find all available Courses. So far we have ' + str(
        cookie_val) + ' times visiting'
    data = {
        'text': text,
    }
    response = render(request, 'myapp/about.html', data)
    response.set_cookie('about_visits', cookie_val, max_age=600)
    return response


# detail page
def detail(request, top_no):
    """
    the detail page of myapp
    """
    topic = Topic.objects.all().filter(id=top_no)
    cours = Course.objects.all().filter(topic_id=top_no)
    data = {
        'topic': topic,
        'cour': cours,
    }
    return render(request, 'myapp/detail.html', data)


def index(request):
    """
       the index page of myapp
       """
    top_list = Topic.objects.all().order_by('id')[:10]
    data = {
        'top_list': top_list,
        'user': request.user,
        'loginInfo': request.session.get('last_login')
    }

    return render(request, 'myapp/index.html', data)


def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})


def place_order(request):
    text = "You can place an order here."
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.order_status = 1
            if order.levels <= order.course.stages:
                stu = order.student
                course = order.course
                level = order.levels
                price = course.discount()
                print(price)
                order.save()
                msg = 'Your course has been ordered successfully.'
                return render(request, 'myapp/order_response.html',
                              {'msg': msg, 'student': stu, 'course': course, 'level': level, 'price': price})
            else:
                msg = 'You exceeded the number of levels for this course.'
                return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist, 'text': text})


def course_detail(request, cour_id):
    if request.method == 'POST':  # show interests in the current course
        form = InterestForm(request.POST)

        print(form)
        # print(form.interested)
        if form.is_valid():
            course = Course.objects.get(id=cour_id)
            # course = form.save(commit=False)
            course.interested += 1
            # print(course.id)
            course.save()
            top_list = Topic.objects.all().order_by('id')[:10]
            data = {
                'top_list': top_list,
                'your_name': "UWindsor",
            }
            return render(request, 'myapp/index.html', data)

    else:
        course = Course.objects.filter(id=cour_id)
        form = InterestForm()
        # form.interested = '1'
        data = {'form': form, 'course': course, 'course_id': cour_id}
        return render(request, 'myapp/course_detail.html', data)


# lab 8
def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        # print(user, username, password)
        if user:
            if user.is_active:
                login(request, user)
                now_time = datetime.datetime.now().strftime('%F %T')
                request.session['last_login'] = str(now_time)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    # logout(request)
    # log out the user by deleting request session
    request.session.flush()
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required
def myaccount(request):
    # if not request.user.is_authenticated():
    #     return redirect('myapp:user_login')
    if request.method == 'POST':

        course_name = request.POST['course_name']
        print(course_name)
        CourseAdmin.add_50_to_hours(course_name)
        data = dict()
        data['error'] = 'You are not a registered student!'
        data['username'] = request.user.username
        data['courses'] = CourseAdmin.courses
        return render(request, 'myapp/myaccount.html', data)
    else:
        students = Student.objects.filter(username=request.user.username)

        data = dict()
        # check the username
        if students.count() == 0:
            data['error'] = 'You are not a registered student!'
            data['username'] = request.user.username
            data['courses'] = CourseAdmin.courses
        else:
            # The first and last name of the student.
            # All the courses that have been ordered by the student.
            # All the topics the student is interested in.
            # for stu in students:
            data['first_name'] = students[0].first_name
            data['last_name'] = students[0].last_name
            data['orders'] = Order.objects.filter(student_id=students[0].user_ptr_id)
            # all_topics = students[0].interested_in
            # print(all_topics.all())
            data['interested_topics'] = students[0].interested_in.all()

        return render(request, 'myapp/myaccount.html', data)




def test_cookie(request):
    """ this is for testing the cookies """
    cookie_val = request.COOKIES.get('cookie_name', None)
    if cookie_val is None:  # no cookies
        response = HttpResponse("First time Visiting")
        response.set_cookie('cookie_name', 'cookie_value')
        return response
    else:  # already has cookies
        return HttpResponse("the cookie name: {}\n, the cookie value: {}".format('cookie_name', cookie_val))


def reset_pwd(request):
    if request.method == 'POST':
        email = request.POST['email_address']
        all_emails = User.objects.filter(email=email)
        if email and all_emails:
            print("We've found the account!")
            send_email(email)
            return render(request, 'myapp/resetpwd_done.html')
        else:
            return render(request, 'myapp/resetpwd_error.html', {
                'msg': 'The email has not been registered yet or the input is illegal! Please check it!'})
    return render(request, 'myapp/resetpwd.html')


def send_email(target_email):
    email_subject = 'Reset Password'
    email_content = 'Here is the new password: ' + generate_pwd(target_email)
    # print(email_content)
    sender = 'mysite.django.python@gmail.com'
    recipients = [target_email]
    send_mail(email_subject, email_content, sender, recipients, fail_silently=False)
    print('Done')


def generate_pwd(account_email):
    MAX_LEN = 8
    user = User.objects.get(email=account_email)
    new_pwd = ""
    seed = string.ascii_letters + string.digits + string.punctuation
    for _ in range(MAX_LEN):
        new_pwd += random.choice(seed)
    user.set_password(new_pwd)
    user.save()
    return new_pwd

myapp/templates/myapp/course_detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <p>{{ course.name }}</p>
    {% if course.for_everyone %}

        <h3>This course is not for everyone!!!</h3>
    {% endif %}

    <form action="/myapp/courses/{{ course_id }}/" method="post">
        {% csrf_token %}

        <tr>
            <th><label for="id_interested_0">Interested:</label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <ul id="id_interested">
                    <li><label for="id_interested_0"><input type="radio" name="interested" value="1" required
                                                            id="id_interested_0">
                        Yes</label>

                    </li>
                    <li><label for="id_interested_1"><input type="radio" name="interested" value="0" required
                                                            id="id_interested_1">
                        No</label>

                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <th><label for="id_levels">Levels:</label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <input type="number" name="levels" required id="id_levels"></td>
        </tr>
        <tr>
            <th><label for="id_comments">Additional Comments:</label></th>
            <td><textarea name="comments" cols="40" rows="10" id="id_comments">
</textarea></td>
        </tr>
        <input type="submit" value="submit">
    </form>
{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h3>List of available courses</h3>
    <p>
        {% for course in courlist %}
            {# use url namespacing to get the url of each topic page #}
            <a href="{% url 'myapp:course_detail' cour_id=course.id %}">
{#            <a href="{% url 'myapp:detail' top_no=top.id %}">#}
                {{ course.name }}
            </a>
            <br>
        {% endfor %}
    </p>
    <p><a href="{% url 'myapp:place_order' %}">Place order (URL namespacing)</a></p>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    {% if user.username %}
        {# already a registered user #}
        {% if user.last_name and user.first_name %}
            Hello {{ user.first_name }} {{ user.last_name }}
        {% else %} {# for the account which doesn't have the first and lat name #}
            Hello {{ user.username }}
        {% endif %}
        <div>
            <span> <a href="{% url 'myapp:my_account' %}">My Account</a> </span>
            <span> <a href="{% url 'myapp:user_logout' %}">Log Out</a> </span>
        </div>

        <br>
        <h3 style="text-align: center">Last login: {{ loginInfo }}</h3>
        {% else %}
        {# not a registered user #}
        Welcome visitor
        <div>
            <span> <a href="{% url 'myapp:index' %}">Register Here</a> </span> {# should be register page #}
            <span> <a href="{% url 'myapp:user_login' %}">Log In</a> </span>
        </div>
        <br>
        <h3 style="text-align: center">Your last login was one hour ago</h3>
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if top_list %}
    <h2>List of Topics</h2>
    <ol>
        {% for top in top_list %}
            {# use url namespacing to get the url of each topic page #}
            <a href="{% url 'myapp:detail' top_no=top.id %}">
                <li>{{ top.name }} </li>
            </a>
        {% endfor %}
    </ol>
{% else %}
    <strong>There are no available topics!</strong>
{% endif %}
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    {% if error %}
        Welcome {{ username }}
        {% else %}
        Welcome {{ first_name }} {{ last_name }}
    {% endif %}

{% endblock %}

{% block body_block %}
    {% if error %}
        <table border="1">
            <tr>
                <th>Topic</th>
                <th>Name</th>
                <th>Price</th>
                <th>Hours</th>
                <th>For Everyone</th>
                <th> Add hours </th>
            </tr>
            <tr>
            {% for course in courses %}
            <tr>
                <td> {{ course.topic }}</td>
                <td> {{ course.name }}</td>
                <td> {{ course.price }} </td>
                <td> {{ course.hours }} </td>
                {% if course.for_everyone %}
                    <td> Yes </td>
                {% else %}
                    <td> No </td>
                {% endif %}

                <td>
                    <form action="{% url 'myapp:my_account' %}" method="post">
                        {% csrf_token %}
                        <input id="course_name" type="text" name="course_name" value="{{ course.name }}">
                        <input type="submit" value="add">
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tr>
        </table>
        {% else %}
        <p> First Name: {{ first_name }} </p>
        <p> Last Name: {{ last_name }} </p>
        <p> Ordered Courses: </p>
        <table border="1">
            <tr>
                <th>Order Date</th>
                <th>Name</th>
                <th>Price</th>
                <th>For Everyone</th>
                <th>Description</th>
            </tr>
            {% for order in orders %}
            <tr>
                <td> {{ order.order_date }}</td>
                <td> {{ order.course.name }}</td>
                <td> {{ order.course.price }} </td>
                {% if order.course.for_everyone %}
                    <td> Yes </td>
                {% else %}
                    <td> No </td>
                {% endif %}
                <td> {{ order.course.description }} </td>
            </tr>
            {% endfor %}
         </table>
        <p> Interested Topic: </p>
        <table border="1">
            <tr>
                <th>Name</th>
                <th>Category</th>
            </tr>
            {% for topic in interested_topics %}
            <tr>
                <td> {{ topic.name }}</td>
                <td> {{ topic.category }}</td>
            </tr>
            {% endfor %}
         </table>
    {% endif %}
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h2>{{ text }}</h2>
    <h3>List of courses and form</h3>

    <form action="/myapp/place_order/" method="post">
        {% csrf_token %}

        <tr>
            <th><label for="id_student_0">Student:</label></th>
            <td>
                <ul class="errorlist">
                    <li>Select a valid choice. That choice is not one of the available choices.</li>
                </ul>
                <ul id="id_student" class="radio">
                    <li><label for="id_student_0"><input type="radio" name="student" value="1" class="radio" required
                                                         id="id_student_0">
                        ---------</label>

                    </li>
                    <li><label for="id_student_1"><input type="radio" name="student" value="2" class="radio" required
                                                         id="id_student_1">
                        Username: john, City:WS, Address: 123 University Avenue</label>

                    </li>
                    <li><label for="id_student_2"><input type="radio" name="student" value="3" class="radio" required
                                                         id="id_student_2">
                        Username: mary, City:VC, Address: 235 Sunset Avenue</label>

                    </li>
                    <li><label for="id_student_3"><input type="radio" name="student" value="4" class="radio" required
                                                         id="id_student_3">
                        Username: alan, City:CG, Address: 306 Prince Street</label>

                    </li>
                    <li><label for="id_student_4"><input type="radio" name="student" value="5" class="radio" required
                                                         id="id_student_4">
                        Username: josh, City:MR, Address: 442 Sunset Avenue</label>

                    </li>
                    <li><label for="id_student_5"><input type="radio" name="student" value="6" class="radio" required
                                                         id="id_student_5">
                        Username: chris, City:WS, Address: 987 King Street</label>

                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <th><label for="id_course">Course:</label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <select name="course" required id="id_course">
                    <option value="0" selected>---------</option>

                    <option value="1">Topic: Name: IT Certification, Category: IT &amp; Software, Name: CCNA, Price:
                        199.99, For_everyone: False, Description: 1. CCNA IT Certification 199.99 F
                    </option>

                    <option value="2">Topic: Name: IT Certification, Category: IT &amp; Software, Name: AWS, Price:
                        119.99, For_everyone: True, Description: 2. AWS IT Certification 119.99 T
                    </option>

                    <option value="3">Topic: Name: IT Certification, Category: IT &amp; Software, Name: CompTIA
                        Security, Price: 139.99, For_everyone: False, Description:
                    </option>

                    <option value="4">Topic: Name: IT Certification, Category: IT &amp; Software, Name: Oracle SQL,
                        Price: 159.99, For_everyone: False, Description:
                    </option>

                    <option value="5">Topic: Name: Economics, Category: Finance &amp; Accounting, Name: Global
                        Economics, Price: 149.99, For_everyone: True, Description:
                    </option>

                    <option value="6">Topic: Name: Economics, Category: Finance &amp; Accounting, Name: Introduction to
                        Economics, Price: 174.99, For_everyone: True, Description:
                    </option>

                    <option value="7">Topic: Name: Economics, Category: Finance &amp; Accounting, Name: Microeconomics,
                        Price: 199.99, For_everyone: False, Description:
                    </option>

                    <option value="8">Topic: Name: Web Development, Category: Development, Name: Web Dev Bootcamp,
                        Price: 199.99, For_everyone: True, Description:
                    </option>

                    <option value="9">Topic: Name: Web Development, Category: Development, Name: Web Design, Price:
                        159.99, For_everyone: False, Description:
                    </option>

                    <option value="10">Topic: Name: Web Development, Category: Development, Name: Web Development
                        Mastercalss, Price: 124.99, For_everyone: True, Description:
                    </option>

                    <option value="11">Topic: Name: Web Development, Category: Development, Name: Build Responsive
                        Websites, Price: 149.99, For_everyone: False, Description:
                    </option>

                    <option value="12">Topic: Name: Management, Category: Business, Name: Innovation for Business,
                        Price: 174.99, For_everyone: True, Description:
                    </option>

                    <option value="13">Topic: Name: Management, Category: Business, Name: Leadership Skills, Price:
                        184.99, For_everyone: True, Description:
                    </option>

                    <option value="14">Topic: Name: Management, Category: Business, Name: Project Management, Price:
                        149.99, For_everyone: True, Description:
                    </option>

                    <option value="15">Topic: Name: Sports, Category: Health &amp; Fitness, Name: Sports Psychology,
                        Price: 174.99, For_everyone: True, Description:
                    </option>

                    <option value="16">Topic: Name: Sports, Category: Health &amp; Fitness, Name: Swimming Guide for
                        Beginners, Price: 99.99, For_everyone: True, Description:
                    </option>

                    <option value="17">Topic: Name: Sports, Category: Health &amp; Fitness, Name: Introduction to
                        Soccer, Price: 134.99, For_everyone: True, Description:
                    </option>

                </select></td>
        </tr>
        <br>
        <tr>
            <th><label for="id_levels">Levels:</label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <select type="number" name="levels" required id="id_levels">
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                </select>
            </td>
        </tr>
        <br>
        <tr>
            <th><label for="id_order_date_month">Order date:</label></th>
            <td>
                <ul class="errorlist">
                    <li>This field is required.</li>
                </ul>
                <select name="order_date_month" required id="id_order_date_month" class="years=date.today()">
                    <option value="1">January</option>
                    <option value="2">February</option>
                    <option value="3">March</option>
                    <option value="4">April</option>
                    <option value="5">May</option>
                    <option value="6">June</option>
                    <option value="7">July</option>
                    <option value="8">August</option>
                    <option value="9">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>

                <select name="order_date_day" required id="id_order_date_day" class="years=date.today()">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                    <option value="31">31</option>
                </select>

                <select name="order_date_year" required id="id_order_date_year" class="years=date.today()">
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                    <option value="2026">2026</option>
                    <option value="2027">2027</option>
                    <option value="2028">2028</option>
                    <option value="2029">2029</option>
                </select>

                <input type="hidden" name="initial-order_date" id="initial-id_order_date">

            </td>
        </tr>

        <input type="submit" value="submit">
    </form>


{% endblock %}

myapp/templates/myapp/resetpwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset Password</title>

</head>
<body>
    <h2>Reset Your Password</h2>
    <p> Please enter your account's email address, and you will receive the new password.</p>
    <form action="{% url 'myapp:reset_pwd' %}" method="post">
        {% csrf_token %}
        <input type="text" name="email_address" placeholder="email address"><br>
        <input type="submit" name="submit" value="Reset My Password"><br>
    </form>

{# <a href="{% url 'myapp:send_email' %}">send email</a> #}
</body>
</html>